language: node_js
node_js: 
  - "12"
script:
  - echo '******Build starts******'
  - echo 'Installing Dependecies'
  - npm install  
  - echo 'Running tests'
  - npm test
branches:
  only:
  - master
  - development

